#!/usr/bin/env sh

export GIT_EDITOR=$VIM

# Should be in a toplevel ~/.zsh_profile
#export DOTFILES=~/.dotfiles



#export NRDP=~/work/nrdp
#export NRDP_BUILDS=~/work/builds
#export CC=clang-12
#export CXX=clang++-12
#export PYTHONBREAKPOINT=pudb.set_trace
#export GOPATH=~/go
#export DARWINS_DIR=~/work/darwins
#export API_TOOLS=~/work/tools/edge/scripts
#export EOSIO_INSTALL_DIR=~/personal/eos
#export NF_IDFILE=~/.idfile
#export DENO_INSTALL=~/.deno
#export N_PREFIX=~/.local/n
#export BOGART=~/work/bogart

