#!/usr/bin/env bash

if [ $(id -u) = 0 ]; then
    # root has no android sdk and should not have actually
    # (will totally ruin permissions)
    return
fi

if [ -d /opt/android-sdk ]; then
    export ANDROID_HOME=/opt/android-sdk
    NDK_VER="$(find "$ANDROID_HOME/ndk" -maxdepth 1 -type d ! -name ndk | head -1)"
    [ -n "$NDK_VER" ] && export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$NDK_VER
    export ANDROID_TOOLS=$ANDROID_HOME/cmdline-tools/latest/bin
    export ANDROID_PLATFORM_TOOLS=$ANDROID_HOME/platform-tools

    addToPathFront "$ANDROID_NDK_HOME"
    addToPathFront "$ANDROID_PLATFORM_TOOLS"
    addToPathFront "$ANDROID_TOOLS"
    addToPathFront "$ANDROID_HOME"
fi

