#!/usr/bin/env bash

#export NRDP=$HOME/work/nrdp
#export NRDP_BUILDS=$HOME/work/builds
#export CC=clang-12
#export CXX=clang++-12
#export PYTHONBREAKPOINT=pudb.set_trace
#export GOPATH=$HOME/go
#export DARWINS_DIR=$HOME/work/darwins
#export API_TOOLS=$HOME/work/tools/edge/scripts
export GIT_EDITOR=$VIM
#export EOSIO_INSTALL_DIR=$HOME/personal/eos
#export NF_IDFILE=$HOME/.idfile
#export DENO_INSTALL=$HOME/.deno
#export N_PREFIX=$HOME/.local/n
export DOTFILES=$HOME/.dotfiles
#export BOGART=$HOME/work/bogart

