#!/usr/bin/env zsh
# Setup fzf
# ---------
#if [[ ":$PATH:" != *":$HOME/.fzf/bin:"* ]]; then
#  #PATH="$HOME/.fzf/bin:$PATH"
#  #PATH="${PATH:+${PATH}:}$HOME/.fzf/bin"
#fi
addToPathFront ~/.fzf/bin

# Auto-completion
# ---------------
source ~/.fzf/shell/completion.zsh

# Key bindings
# ------------
#source ~/.fzf/shell/key-bindings.zsh

