#https://alacritty.org/config-alacritty.html

[general]
#working_directory = "~"
live_config_reload = true

[window]
decorations = "Full" # "None"  # "Full"
opacity = 0.93
startup_mode = "Maximized"  # "Windowed"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key   = "Back", mods  = "Control", chars = "\u0017" } # Ctrl+w alias to Ctrl+Backspace
]

[colors.normal]
#blue = "#69b9f6"

[font]
#normal = { family = "Fira Code", style = "Regular" } #def=Consolar Regular
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" } #def=Consolas Regular
size = 11.25 #def=11.25
builtin_box_drawing = true #def=true
offset = { x = 1, y = 0 }
#glyph_offset = { x = 0, y = 0 }

